name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: vuepress-deploy
        uses: Leadgq/vue-preess@master
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          TARGET_REPO: Leadgq/vue-preess
          TARGET_BRANCH: master
          BUILD_SCRIPT: npm && npm docs:build
          BUILD_DIR: blog/.vuepress/dist/
